// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20191026193427_RemovedUnneccessaryFields")]
    partial class RemovedUnneccessaryFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entities.ChildModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<Guid>("FactoryId");

                    b.Property<Guid?>("FactoryModelId");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("FactoryModelId");

                    b.ToTable("child");
                });

            modelBuilder.Entity("Entities.FactoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<int>("RangeHigh");

                    b.Property<int>("RangeLow");

                    b.Property<Guid>("RootId");

                    b.Property<Guid?>("RootTreeModelId");

                    b.HasKey("Id");

                    b.HasIndex("RootTreeModelId");

                    b.ToTable("factory");
                });

            modelBuilder.Entity("Entities.RootTreeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.HasKey("Id");

                    b.ToTable("root");
                });

            modelBuilder.Entity("Entities.ChildModel", b =>
                {
                    b.HasOne("Entities.FactoryModel")
                        .WithMany("Childs")
                        .HasForeignKey("FactoryModelId");
                });

            modelBuilder.Entity("Entities.FactoryModel", b =>
                {
                    b.HasOne("Entities.RootTreeModel")
                        .WithMany("Factories")
                        .HasForeignKey("RootTreeModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
