// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Entities;

namespace ListChallengeServer.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20191026134108_Initial Create")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ListChallengeServer.ChildModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<Guid>("FactoryId");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("child");
                });

            modelBuilder.Entity("ListChallengeServer.FactoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<int>("RangeHigh");

                    b.Property<int>("RangeLow");

                    b.Property<Guid>("RootId");

                    b.HasKey("Id");

                    b.HasIndex("RootId");

                    b.ToTable("factory");
                });

            modelBuilder.Entity("ListChallengeServer.RootTreeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.HasKey("Id");

                    b.ToTable("root");
                });

            modelBuilder.Entity("ListChallengeServer.ChildModel", b =>
                {
                    b.HasOne("ListChallengeServer.FactoryModel", "Factory")
                        .WithMany("Childs")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ListChallengeServer.FactoryModel", b =>
                {
                    b.HasOne("ListChallengeServer.RootTreeModel", "Root")
                        .WithMany("Factories")
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
